### ISSUE TITLE
Should be able to let app manage the Category

### ISSUE THREAD

**Issue by kevinzhow** [adamcichy/SwiftySound#13]
Swift sound forced to set one category, which will conflict with the App's sound category settings.

**Comment by adamcichy** [comment]
Hi @kevinzhow,

SwiftySound has an option of changing the sound category. For example:

        Sound.category = .playback

For all options please take a look at the `SoundCategory` enum. It is a wrapper over `AVAudioSession` category constatns.

**Comment by kevinzhow** [comment]
What if I want set category with flags?

```
session.setCategory(AVAudioSessionCategoryPlayAndRecord, with: [.mixWithOthers])
```

SwiftSound will override my flags

**Comment by adamcichy** [comment]
That is not supported currently. I will keep that in mind for future release. As a temporary workaround, you could do this:

```swift
Sound.category = .playAndRecord
AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayAndRecord, with: [.mixWithOthers])
```
