### ISSUE TITLE
Can it play in background?

### ISSUE THREAD

**Issue by brandy2015** [adamcichy/SwiftySound#14]
When app enter backgound ,the music will stop. Is there exits any solutions?

**Comment by adamcichy** [comment]
Hi @brandy2015,
For background playback, you need two things:

1. Set the category to `.playback`.

        Sound.category = .playback


2. Set background modes for audio playback. See this link for inatructions:
[Background Execution](https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html)

**Comment by brandy2015** [comment]
Thank you very much! As your way , it works.
