### ISSUE TITLE
Crash in iOS 11 GM

### ISSUE THREAD

**Issue by tfsjohan** [adamcichy/SwiftySound#15]
Sound init?(url: URL) is crashing when loading a sound in iOS 11 GM. It is called like this:

scanSound = Sound(url: Bundle.main.url(forResource: "beep-sound", withExtension: "mp3")!)

The file exists and the URL is not nil.

**Comment by adamcichy** [comment]
Please run this code and see what is being printed in the console:

        if let url = Bundle.main.url(forResource: "beep-sound", withExtension: "mp3") {
            let scanSound = Sound(url: url)
        }
        else {
            print("no file")
        }

If there is a crash, please share the crash log.

**Comment by tfsjohan** [comment]
That actually works. Strange, since I could see that the URL was not nil in init(url: url). The sounds loads and plays as expected with this version, but not when Bundle....! is inlined.
