### ISSUE TITLE
Pause And Resume?

### ISSUE THREAD

**Issue by giodss** [adamcichy/SwiftySound#20]
Awesome library! Do you think you can further improve with pause and resume method? Thanks!

**Comment by adamcichy** [comment]
Thanks for your suggestion. I’ll look into it. Should be possible to add these methods.

**Comment by giodss** [comment]
Much Appreciated!

**Comment by aloveric** [comment]
+1

**Comment by AppDevGuy** [comment]
+1

**Comment by giuliom92** [comment]
it could be great I also need these two methods ... for now I'm using stop instead of pause
