### ISSUE TITLE
no sound on iOS 11

### ISSUE THREAD

**Issue by jhancock** [adamcichy/SwiftySound#26]
Our app plays sound on iOS 10, but after upgrade to iOS 11, the mp3s don't have any sound.  They do seem to be "playing" as we can time aspects of the app to see that a event doesn't happen until after the file should have completed.  But no volume.  We can hear the sound on the simulator but not the iPad or iPhone device. We've played with the volume setting and a few others but no luck.  Debugging doesn't show any errors.  The sound objects look about right.
Any ideas to debug this?

**Comment by adamcichy** [comment]
Can you please share the `mp3` file?

**Comment by jhancock** [comment]
Hi Adam, the mp3s are of my 12 year son reading.  I'm not too comfortable posting these public...I know...the app it sits in is sort of public on the AppStore...anyhow...hope you won't mind if I ping you over email.

The key part of code that creates and uses the Sound object is:

        let url = Bundle.main.url(forResource: fileName, withExtension: "mp3")!
        pageTextSound = Sound(url: url)
        pageTextSound.volume = 1.0  // added after bug surfaced to ensure we have volume set
        pageTextSound.play()  { completed in
            if self.readToMe == true {
                self.run(SKAction.sequence([self.readToMeNextPageDelay, SKAction.run { self.nextPage() } ]))
            }
        }

I've added various debug output and stepped through with debugger and it seems all is working as expected.  This is a children's storybook.  Each page's sound has different time lengths.  You can see "completed in" block...the block does only trigger after the correct time for that page's length has passed.  It seems like the mp3 is playing...just no sound on the device...only get sound on simulator (iOS 10 and 11) and on device (iOS 10).

**Comment by adamcichy** [comment]
@jhancock No problem at all, you can send the file to me at adam@moonlightapps.com

**Comment by jhancock** [comment]
Hi Adam...all clear.  As near as I can tell the problem may have been with the ringer on the phone being off.  We are fairly certain this didn't effect things on iOS 10, but does seem to surface on iOS 11. 
Anyhow...not a bug with your excellent library.  thanks
