### ISSUE TITLE
SwiftySound initialization error: Error Domain=NSOSStatusErrorDomain Code=2003334207 "(null)"

### ISSUE THREAD

**Issue by rahulmehndiratta** [adamcichy/SwiftySound#29]
SwiftySound initialization error: Error Domain=NSOSStatusErrorDomain Code=2003334207 "(null)"

**Comment by adamcichy** [comment]
This error (2003334207) probably thrown because the sound file doesn't exist. Please check if you are using the right file name and come back with results.

**Comment by jerrypm** [comment]
Don't change format data example: "from do.wav to do.mp3"
you must check file may be the file is corrupt

**Comment by vokhuyetOz** [comment]
it happen if i use remote URL
