### ISSUE TITLE
Minimum Target Version is set to 10.2

### ISSUE THREAD

**Issue by Dschee** [adamcichy/SwiftySound#3]
Is iOS 10.2 really required? For what? I'd like to use it for iOS 10.0 at least ...

**Comment by adamcichy** [comment]
Swifty sound supports iOS 8 and later. Where did you get that information from?

**Comment by Dschee** [comment]
Xcode told me after importing the library via Carthage. ;)

**Comment by Domsware** [comment]
Problem is still here: I wanted to try SoundSwift today so added the given command to `cart file`.
