### ISSUE TITLE
Why `init?(name: String)` was removed in 1.0.0?

### ISSUE THREAD

**Issue by rivera-ernesto** [adamcichy/SwiftySound#35]
Up to 0.7.0 I could load sound files for xcassets. Now it is hard and cumbersome to manually create a `URL` out of a `NSDataAsset`.

Is there a particular reason for removing this? Would it be bad to at least keep `init?(data: Data)`?

Thanks!

**Comment by adamcichy** [comment]
Hi @rivera-ernesto that functionality is a part of your open pull request. It was not merged. That pull request has some unresolved issues and conflicts with current master.
