### ISSUE TITLE
Hello. I would like to know if you are going to release a version for Swift 4.2

### ISSUE THREAD

**Issue by manuelsBTS** [adamcichy/SwiftySound#38]
Hello. I would like to know if you are going to release a version for Swift 4.2

**Comment by adamcichy** [comment]
Yes, there’s a plan to support Swift 4.2

**Comment by manuelsBTS** [comment]
Great @adamcichy This is the last repository that I have in my project with missing support for Swift 4.2 

glad to hear that

**Comment by fassko** [comment]
@adamcichy I was trying to convert to Swift 4.2. Can you explain what's the deal with `extension AVAudioSession: Session` Can you tell more how are you using that? Thanks! If you can help here I'm halfway to make a PR.

**Comment by fassko** [comment]
I think it's not possible because of https://forums.swift.org/t/using-methods-marked-unavailable-in-swift-4-2/14949

I don't think this library should introduce some wiggling with Objective-C.

**Comment by adamcichy** [comment]
@fassko That is the issue. I'd rather not introduce any Objective-C workarounds. There is also an option of using `performSelector:...` from Swift but that's also not perfect

**Comment by fassko** [comment]
@adamcichy I agree with you. That’s why I like his library as it’s Objective-C free. Let’s hope Swift team will fix it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by aloveric** [comment]
+1

**Comment by aloveric** [comment]
Swift 4.2

#if os(iOS) || os(tvOS)
/// SoundCategory is a convenient wrapper for AVAudioSessions category constants.
    public enum SoundCategory {

        /// Equivalent of AVAudioSessionCategoryAmbient.
        case ambient
        /// Equivalent of AVAudioSessionCategorySoloAmbient.
        case soloAmbient
        /// Equivalent of AVAudioSessionCategoryPlayback.
        case playback
        /// Equivalent of AVAudioSessionCategoryRecord.
        case record
        /// Equivalent of AVAudioSessionCategoryPlayAndRecord.
        case playAndRecord

        fileprivate var avFoundationCategory: String {
            get {
                switch self {
                case .ambient:
                    return convertFromAVAudioSessionCategory(AVAudioSession.Category.ambient)
                case .soloAmbient:
                    return convertFromAVAudioSessionCategory(AVAudioSession.Category.soloAmbient)
                case .playback:
                    return convertFromAVAudioSessionCategory(AVAudioSession.Category.playback)
                case .record:
                    return convertFromAVAudioSessionCategory(AVAudioSession.Category.record)
                case .playAndRecord:
                    return convertFromAVAudioSessionCategory(AVAudioSession.Category.playAndRecord)
                }
            }
        }
    }
#endif

fileprivate func convertFromAVAudioSessionCategory(_ input: AVAudioSession.Category) -> String {
	return input.rawValue
}

**Comment by adamcichy** [comment]
SwiftySound has been updated to Swift 5 now

**Comment by mtangoo** [comment]
Some of us won't update to Mojave anytime soon. So it means we can't use this library

**Comment by mtangoo** [comment]
For Swift 4.2 pin carthage at version 1.0.0
