### ISSUE TITLE
Sound doesn't play when created as an object

### ISSUE THREAD

**Issue by slifty** [adamcichy/SwiftySound#40]
First: thank you for this library!  Super helpful.
Second: I may be doing something very silly.

I have a sound in an mp3 file.  When I play it using the Sound class, it works:

```
let audioUrl = "path/that/works.mp3"
Sound.play(url:audioUrl)
```

However, if I try to play from an instance of a sound object, it does not actually play any sound (and does not ever call back a completion event):

```
let audioUrl = "path/that/works.mp3"
let mySound = Sound(url: audioUrl)
mySound!.play()
```

Any clues as to what might be going on?  When I debug and follow the control flow it seems to be calling all the right things, ultimately ending on `return play()` in line 353 of Sound.swift

Thoughts appreciated.

**Comment by Fedenieto90** [comment]
Hi! @slifty I'm facing the same problem when creating an instance of a sound object. How did you solve it?

**Comment by slifty** [comment]
@Fedenieto90 So caveat that I'm not an expert on Swift, but it seems that if you create the object within a method, it appears the object loses scope and gets cleaned up immediately after the function ends.  This is different from how things work out in, for instance, Node, where you can trigger a promise and it will resolve later.

I had to make the instance a class variable, so that it wouldn't get removed from memory right after the method finished.

Here is the commit / line where I played the sound -- https://github.com/BadIdeaFactory/arobotherapy/commit/7de5bbcdef59386ebbe9b428e38421a6ee8c818d#diff-e3089959bce5859a9a8a8e6f0e5af7abR83

**Comment by Fedenieto90** [comment]
Thanks! 👍

**Comment by adamcichy** [comment]
@slifty This is exactly the reason why the object is released immediately. Creating an object and releasing it right after it's created is not currently supported but it might make sense in some cases. I'll think about it, maybe there is a point of retaining the object whenever it starts playing
