### ISSUE TITLE
is it possible to use it with a PageControl?

### ISSUE THREAD

**Issue by MagdiejamesNYC** [adamcichy/SwiftySound#41]
Hi
Is it possible to use SwiftySound with a pageControl? I mean for example launching a sound when someone swipe to a new page, without having to press a play button? thx for your feedback on that

**Comment by adamcichy** [comment]
Of course it's possible. Not really related to the library itself, but take a look at [valueChanged](https://developer.apple.com/documentation/uikit/uicontrol/event/1618238-valuechanged) event that is triggered each time when a page is changed
