### ISSUE TITLE
completion block is only called once

### ISSUE THREAD

**Issue by artangco** [adamcichy/SwiftySound#44]
I created an instance of a sound and when I need to play it again I'm using the same instance to replay it.  What I've noticed that is that if I have a completion block for this sound instance the completion block is only called the first time the sound is played.  If I play the sound again the completion block is not called again.

**Comment by adamcichy** [comment]
I tried to reproduce this issue but it works fine for me. I'm using the example app, you check the code from the example app and compare with yours. If that wont help, please provide some example code
