### ISSUE TITLE
Swift Package manager can not import into Xcode (11b3)

### ISSUE THREAD

**Issue by LordAndrei** [adamcichy/SwiftySound#48]
Xcode SPM import error:

The package dependency graph can not be resolved, possibly because of these requirements:
https://github.com/adamcichy/SwiftySound.git — 1.1.0..<2.0.0

Using WWDC19 Beta 3 across the board.

**Comment by tsfischer** [comment]
Just ran into the same issue, trying to play around with SPM.

**Comment by furiosFast** [comment]
same issue

**Comment by legolasW** [comment]
Confirmed it's fixed now. I can import using SPM without any issue.

**Comment by adamcichy** [comment]
This has been fixed in https://github.com/adamcichy/SwiftySound/pull/50
