### ISSUE TITLE
Inconsistencies between static methods and instances

### ISSUE THREAD

**Issue by trentjones21** [adamcichy/SwiftySound#55]
This is working for me:

```swift
let fileURL = Bundle.main.url(forResource: "MyMusic", withExtension: "mp3")!
Sound.play(url: fileURL) // Music plays
```
While this is not
```swift
let fileURL = Bundle.main.url(forResource: "MyMusic", withExtension: "mp3")!
let mySound = Sound(url: fileURL)!
mySound.play()
```

I'm running both these snippets in the exact same spot in my code, so I have no idea why one would work and the other wouldn't.  May very well be user error, but I think I'm following the documentation correctly.

**Comment by trentjones21** [comment]
I fixed the issue by moving the reference to the Sound instance to a higher scope

**Comment by aloveric** [comment]
Same for me. It is not working.

let mySound = Sound(url: fileURL)
mySound.play()
