### ISSUE TITLE
What about preloading sound? — Question

### ISSUE THREAD

**Issue by Domsware** [adamcichy/SwiftySound#7]
In previous projects I used to preload sounds. As I didn't find any mention of this for SwiftySound I wonder if it's a missing part.

**Comment by adamcichy** [comment]
The only thing you need to do is:
```swift
Sound.play("yoursound.mp3")
```
Preloading is not necessary to play a sound. It will work without preloading just fine.

If you are referring to `prepareToPlay` method of `AVAudioPlayer`, SwiftySound doesn't make that call. But it might be worth adding a static variable to control that.

**Comment by Domsware** [comment]
Ok. I remembered having to preload sounds at the begin on an old project .
